apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harishkumarnimmala/application-deployment-on-onpremise-kubernetes-using-github-actions-and-argocd.git
    targetRevision: HEAD
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/harishkumarnimmala/frontend-app
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
